server: #server config
  port: 8080
  
spring:
  main: #spring boot config
    banner-mode: "off" #关闭banner

  jackson:
    dateFormat: yyyy-MM-dd HH:mm:ss
    timeZone: GMT+8

  datasource: #data source config
    url: jdbc:mysql://127.0.0.1:3306/gjf?useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: 123456
    driverClassName: com.mysql.jdbc.Driver
    initScriptFile: /sql/init.sql
    
  jpa: #jpa config
    database: MYSQL
    show-sql: true
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
      
  messages: #i18n config
    basename: i18n/messages
   
  thymeleaf: #thymeleaf config
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false

shiro:
  password: #控制密码相关配置
    retryCount: 5 #密码最多输入错误数

  kickout: #控制同一账号同时登陆人数
    maxSession: 1 #同时登陆最大人数
    kickoutAfter: false #踢出方式(false:踢出第一个登陆,true:最后个无法登陆)

  cookie: #控制cookie相关配置
    maxAge: -1 #过期时间(-1:永不过期,单位:分钟)
    rememberMeMaxAge: 43200 #记住我cookie过期时间(默认30天,单位为"分钟")

  session: #控制session相关配置
    timeOut: 30 #session超时时间(单位:分钟)
    cluster: false # session是否集群共享(true:需要配置下面redis参数,session保存至redis,false:session保存至内存,不共享单机环境)
    redis:
      database: 0 # Redis数据库索引（默认为0)
      host: 127.0.0.1
      port: 6379
      password:
      timeout: 0
      pool:
        maxActive: 8
        maxWait: -1
        maxIdle: 8
        minIdle: 0